version: '3.9'
services:
  canvas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    command:
      - -port
      - ':8080'
    depends_on:
      - redis

  redis:
    image: bitnami/redis:6.0
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6009:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
